course_name = "机器学习概论"
course_code = "AUTO3019"
notices = ""

[[lecturers]]
name = "熊昊"
  [[lecturers.reviews]]
  content = """
  有时考勤，发一张表格让大家写名字。
  讲解不算清晰。
  """
  [lecturers.reviews.author]
  name = "Oliver Wu"
  link = "https://github.com/OliverWu515"
  date = "2025-01-01"

textbooks = []

[[online_resources]]
title = "国立台湾大学李宏毅教授 2021 年春季机器学习课程"
url = "https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.php"
description = "本课程完全照搬此课程，课程视频发布在 Youtube，B 站也有人搬运。"
[online_resources.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = "2025-01-01"

[[online_resources]]
title = "Introduction to Generative AI (2024 Spring)"
url = "https://speech.ee.ntu.edu.tw/~hylee/genai/2024-spring.php"
description = "推荐李宏毅老师开设的生成式人工智能导论。"
[online_resources.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = "2025-01-01"

[[course]]
content = """
作业、期末报告、大作业都是三人一组。
期末报告内容是：从一系列主题（见 assignments/2024 文件夹下的 Presentation.pptx）选取一个，做 ppt 并演讲。
平时作业有三个（每个 10 分），具体内容见 assignments/2024 文件夹（作业 2 文件量比较大，所以放在校内网盘里面了）。大作业同样见文件夹。
"""
[course.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = "2025-01-01"

[[exam]]
content = "成绩构成：平时10%，作业30%，报告20%，期末大作业40%。"
[exam.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = "2025-01-01"

[[advice]]
content = "强烈建议大家看网课而不是选你校这门二手课。"
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = "2025-01-01"

schedule = []
related_links = []
misc = []